### ISSUE TITLE
Obfuscate the lat lng data

### ISSUE THREAD

**Issue by minhkhang1795** [airpartners/aq-web-client#1]
The lat lng data was obfuscated but in a very absurd way. We need to pick better default geo locations and update the `deviceInitData` variable in `Utils.js`.

Scott and QuantAQ researchers said in emails that one thing we could do is to randomly pick a location within a 200 m x 200 m block square.

**Comment by anushadatar** [comment]
We probably need to determine what "absurd" means here; once I get access to quantaq and have access to the exact locations of the sensor boxes, we can ensure what's stated in https://github.com/airpartners/aq-web-client/blob/master/src/Utils.js is within our expected range.

**Comment by anushadatar** [comment]
Discussed this with Scott and received confirmation that the sensor box locations and appropriately obfuscated, so closing this issue for now.
