### ISSUE TITLE
AtAGlance - Present the data correctly

### ISSUE THREAD

**Issue by minhkhang1795** [airpartners/aq-web-client#2]
Before working on this, make sure to talk to Scott about whether the AQI is the standard we should pursue.

Need to calculate AQI and present the color of the cloud correctly.

**Comment by anushadatar** [comment]
Related: [AQI assumption test](https://docs.google.com/document/d/1EtGzySFGZ5PVPhCsywW77AdkwYG_axO-Zp_cfnLsTVg/edit?usp=sharing)
