### ISSUE TITLE
Apply correction factor for small particle data measurements

### ISSUE THREAD

**Issue by anushadatar** [airpartners/aq-web-client#40]
Side-by-side deployments of other particle measurement instruments next to those in the network and determined there is a correction factor for PM1, P2.5, and PM10 data, and its **17x**. There’s a consistent and systematic undercounting issue with the optical measurement (as opposed to a mass-based measurement). We need to increase these values by that factor in the backend.

**Comment by Inkering** [comment]
By PM1, is that the bin0 0.3-0.5 measurement?

**Comment by anushadatar** [comment]
I think it distinctly does not include the 0.3-0..5 measurement, because I feel like I asked that in class (notes are [here](https://docs.google.com/document/d/1_wpN4ma8mhTeq-uEZLZQZz2RgUn9d4GhDovL_Xkc-A8/edit?usp=sharing)) might be worth asking to clarify though

**Comment by Inkering** [comment]
hmm ok, I don't think we even show a distinct PM1 category 🧐

**Comment by Inkering** [comment]
Applied the factors. Even with the corrections the readings are below WHO baselines as we somewhat expected
