### ISSUE TITLE
Update package.json to work on windows or unix... port issue

### ISSUE THREAD

**Issue by Inkering** [airpartners/aq-web-client#43]

**Comment by wFairmanOlin** [comment]
when running npm start, this popped up:

"'PORT' is not recognized as an internal or external command,
operable program or batch file."

Had to change modify the following line in package.json
prev:
    "start": "PORT=3333 && react-scripts start",
new:
    "start": "**set** PORT=3333 && react-scripts start",

**Comment by Inkering** [comment]
the `set` keyword also works on Mac, need to test on linux

**Comment by anushadatar** [comment]
Assigning myself to this to try it on Linux

**Comment by Inkering** [comment]
https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project more info on this peculiarity

**Comment by Inkering** [comment]
Particularly this solution looks ideal

<img width="681" alt="Screen Shot 2021-03-02 at 10 01 52 PM" src="https://user-images.githubusercontent.com/4595970/109746133-e7def880-7ba2-11eb-958c-bba8618c72c5.png">

**Comment by anushadatar** [comment]
2 months later finally added one line of code :)
