### ISSUE TITLE
SN000-046 is no longer in Roxbury

### ISSUE THREAD

**Issue by Inkering** [airpartners/aq-web-client#53]
According to a QuantAQ table from Scott, this sensor has been moved to the revere system. Would be good to verify that and update the location if so...
https://github.com/airpartners/aq-web-client/blob/53b5a73bb762a142914273907c559c17947d6e5b/src/Utils.js#L18-L28

**Comment by anushadatar** [comment]
@Inkering Did you ask Scott about this? If not, should I? Let me know either way.

**Comment by Inkering** [comment]
worth a double check but yes if I recall.
